# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('author', models.CharField(max_length=200)),
                ('keywords', models.CharField(max_length=300)),
                ('year', models.IntegerField(default=2000)),
                ('venue', models.CharField(max_length=200)),
            ],
        ),
    ]
